[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
[tool.poetry.scripts]
dev = "uvicorn src.ecorcon.web:app --reload"
stage = "python -m ecorcon staging"
prod = "python -m ecorcon"
